[profile.default]
solc = '0.8.21'
evm_version='paris'
via_ir = true
src = 'src'
out = 'out'
test = 'test'
libs = ['lib']
optimizer = true
optimizer_runs = 100
ignored_error_codes = []

[fuzz]
runs = 500

[invariant]
runs=500
fail_on_revert = true
depth = 10

[profile.optimized-build]
via_ir = true
evm_version='paris'
script = 'src'
test = 'src'
out = 'out-optimized'

[profile.lite]
solc = '0.8.21'
evm_version='paris'
via_ir = false
optimizer = true
optimizer_runs = 10_000
ignored_error_codes = []

[profile.deep.fuzz]
runs = 10000
evm_version='paris'

[profile.deep.invariant]
runs = 5000
depth = 32
evm_version='paris'

[fmt]
line_length = 115
wrap_comments = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
