name: Modular Account Test CI

on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

# Runs linter, tests, and inspection checker in parallel
jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ./.github/workflows/setup-ci

      - name: "Check formatting"
        run: forge fmt --check

      - name: "Lint the contracts"
        run: "pnpm lint"

  test-optimized-test-deep:
    name: Run Forge Tests (optimized-test-deep)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ./.github/workflows/setup-ci

      - name: Build project
        run: FOUNDRY_PROFILE=optimized-build forge build

      - name: Run tests
        run: FOUNDRY_PROFILE=optimized-test-deep forge test -vvv

  test-default:
    name: Run Forge Tests (default)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ./.github/workflows/setup-ci

      - name: Build project
        run: forge build

      - name: Run tests
        run: forge test -vvv